export interface ICompanyCSVRowData {
  'User FirstName': string;
  'User LastName': string;
  'User Email': string;
  'BOIR Submission Deadline': string;
  'Company Request To Receive Foreign ID': string;
  'Company Foreign Pooled': string;
  'Company Legal Name': string;
  'Company Alternative Name': string;
  'Company Tax Id Type': string;
  'Company Tax Id Number': string;
  'Company Country/Jurisdiction': string;
  'Company Country/Jurisdiction of Formation': string;
  'Company Address': string;
  'Company City': string;
  'Company US or Territory': string;
  'Company State': string;
  'Company Zip code': string;
  'Company Exists': string;
  'Owner Is Parent or Guardian': string;
  'Owner Is Exempt Entity': string;
  'Owner FinCEN ID': string;
  'Owner Last or Legal Name': string;
  'Owner First Name': string;
  'Owner Middle Name': string;
  'Owner Suffix': string;
  'Owner Date of Birth': string;
  'Owner Address': string;
  'Owner City': string;
  'Owner Country/Jurisdiction': string;
  'Owner State': string;
  'Owner Postal Code': string;
  'Owner Document Type': string;
  'Owner Document Number': string;
  'Owner Document Country/Jurisdiction': string;
  'Owner Document State': string;
  'Owner Local or Tribal': string;
  'Owner Other Local or Tribal Description': string;
}
